services:
  db:
    container_name: db_postgresql
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: phi-Journal
      POSTGRES_USER: username
      POSTGRES_PASSWORD: secret
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    container_name: Phi-Journal_api
    image: grinik767/phi-journal:alpha4
    ports:
      - "80:8080"
    depends_on:
      - db
volumes:
  db_data:
